site_name: Bank Risk Management Simulation
site_author: Mingze Gao
site_url: https://bankrisk.org/
site_description: >-
  A bank risk management simulation framework

repo_url: https://github.com/mgao6767/brms
repo_name: brms

copyright: Copyright &copy; 2025 <a href="https://mingze-gao.com">Mingze Gao</a>

extra_css:
  - stylesheets/extra.css

validation:
  links:
    absolute_links: relative_to_docs

theme:
  name: material
  custom_dir: overrides
  favicon: icon.png
  logo: icon.png
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: octicons/log-24
  features:
    - announce.dismiss
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - toc.follow 
    - navigation.prune 
    - navigation.tabs
    - navigation.path
    - navigation.indexes 
    - navigation.top
    - navigation.expand

extra:  
  generator: false
  version:
    provider: mike
    alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mgao6767/brms
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/adriangao
    - icon: fontawesome/solid/paper-plane
      link: mailto:mingze.gao@mq.edu.au

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      exclude:
        - "reference/*"
  - gen-files:
      scripts:
      - scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            preload_modules: [brms]
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            show_bases: true
            show_inheritance_diagram: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            unwrap_annotated: true
nav:
  - Home: index.md
  - Basel III: 
    - basel_3/index.md
    - Risk-Based Capital Requirements: basel_3/rbc.md
    - Definition of Capital: basel_3/capital.md
    - Risk-Weighted Assets (RWA): 
      - basel_3/rwa/index.md
      - RWA for Credit Risk: basel_3/rwa/credit_risk.md
      - RWA for Market Risk: basel_3/rwa/market_risk.md
      - RWA for Operational Risk: basel_3/rwa/operational_risk.md
    - Leverage Ratio: basel_3/lev.md
    - Liquidity Coverage Ratio (LCR): basel_3/lcr.md
    - Net Stable Funding Ratio (NSFR): basel_3/nsfr.md
  - API Reference: reference/