[project]
name = "brms"
version = "0.1.0"
description = "A bank risk management simulation framework."
readme = "README.md"
authors = [{ name = "Mingze Gao", email = "adrian.gao@outlook.com" }]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
    "pyside6==6.8.1",
    "quantlib>=1.36",
    "rich>=13.9.4",
]

[dependency-groups]
dev = ["isort>=5.13.2", "pytest>=8.3.4", "ruff>=0.8.5"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]

[tool.pytest.ini_options]
filterwarnings = [
  # QuantLib
  'ignore:builtin type SwigPyPacked has no __module__ attribute',
  'ignore:builtin type SwigPyObject has no __module__ attribute',
  'ignore:builtin type swigvarlink has no __module__ attribute',
]

[tool.pylint]
extension-pkg-whitelist = ["PySide6"]
